name: 'eval'

dust3r_ckpt: '/home/jialu/nerf/snap_snap/experiments/dust3r_0701_1436/ckpt/dust3r_final.pth'
restore_ckpt: '/home/jialu/nerf/snap_snap/experiments/gs_wo_unet_0714_1117/ckpt/gs_wo_unet_final.pth'

